// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCubEKButRl9yySSe9JMnK6qy61FdpLMpY',
    appId: '1:778905925906:web:a2a38a53eb638f806f1bcb',
    messagingSenderId: '778905925906',
    projectId: 'nike-new',
    authDomain: 'nike-new.firebaseapp.com',
    storageBucket: 'nike-new.appspot.com',
    measurementId: 'G-MRSVDTSFDE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTJstzjMQ8l1ZEGPddcTcmhqXJzwiXeNY',
    appId: '1:778905925906:android:b21943fe858d01036f1bcb',
    messagingSenderId: '778905925906',
    projectId: 'nike-new',
    storageBucket: 'nike-new.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKqRPS7vWAuuGSXK_ckGMSY-AJsrW--NU',
    appId: '1:778905925906:ios:366b4826bc7f1e806f1bcb',
    messagingSenderId: '778905925906',
    projectId: 'nike-new',
    storageBucket: 'nike-new.appspot.com',
    iosBundleId: 'com.example.nikeapp',
  );
}
